import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavComponent from "@/components/navbar";
import FooterComponent from "@/components/Footer";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800']
});


export const metadata: Metadata = {
  title: "EcoPulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">

    <body className={`${poppins.variable}`}>
        <NavComponent/>
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
